### ISSUE TITLE
New UDMPRO OS 2.4.x moves /mnt/data to /data/

### ISSUE THREAD

**Issue by imhotep** [telnetdoogie/UDMP-ipv6#3]
Everything else applies, just the paths have changed.

**Comment by telnetdoogie** [comment]
thank you!!
I have prepared a branch - [`unifiOS-2.4`](https://github.com/telnetdoogie/UDMP-ipv6/tree/unifiOS-2.4) with the updates. Feel free to take a look and comment on the PR #4 
Once 2.4 is more generally available I will update the main branch, otherwise I'll keep it as a separate branch for now.

**Comment by telnetdoogie** [comment]
I don't have 2.4 yet on my own device to thoroughly walk thru and test.

**Comment by telnetdoogie** [comment]
main branch and [2.0.1](https://github.com/telnetdoogie/UDMP-ipv6/releases/tag/2.0.1) released for 2.4+ OS versions.
