### ISSUE TITLE
2 WAN interfaces

### ISSUE THREAD

**Issue by imhotep** [telnetdoogie/UDMP-ipv6#5]
Is this supposed to work when there are 2 WAN interfaces? I see it does substitute eth9 with he-ipv6 but does that work if eth9 is already used for backup internet?

**Comment by telnetdoogie** [comment]
It should (I have 2) - however I think given some of the new functionality where you can re-assign WAN interfaces it made sense to use the 'current' / default WAN...
[#6c1b1e09c192bf63ef0eb39ae2af3f39afd40ab0](https://github.com/telnetdoogie/UDMP-ipv6/commit/6c1b1e09c192bf63ef0eb39ae2af3f39afd40ab0) should make more sense?

Give the updated script a try and give me any feedback.

Also updated for some additional ip6tables entries that didn't exist before OS3.0 (capitalized interface definitions)

**Comment by telnetdoogie** [comment]
I should note.... this updated script will apply the ipv6 rules to your primary WAN, however HE tunnel will only work with a single WAN interface, since it's going to forward your IPv6 traffic to a single specific IP. If there's failover or load balancing across two interfaces, the HE tunnel will not work appropriately in that situation.
In the case of a WAN IP change or failover, I don't expect things to work properly unless I can figure out a way to detect the change and trigger a teardown and re-create.... Noted in Issue #1
